### PR TITLE
Add new Class for "Major" and add it as a variable in "Person"

### PR DESCRIPTION
**Pull request by DanielDSSim**

### CODE REVIEW

**Comment by DanielDSSim** [comment]
#35

**Comment by DanielDSSim** [comment]
Add storage component edits. Will move on to edit add command and parser

**Comment by DanielDSSim** [comment]
Some tests fail as the edit function has not been changed

**Comment by DanielDSSim** [comment]
Should be stable. Only did not edit. UI. Might also not have enough tests implemented.

**Comment by WeeSooJun** [comment]
Many of your code length of each line is more than 120.

**Comment by DanielDSSim** [comment]
I will try to resolve locally then make another pull request

**Pull request closed without merging**
